import type { 
  Activo, 
  Pago, 
  Dividendo, 
  Inversionista, 
  MovimientoFinanciero, 
  Alerta, 
  Usuario,
  RegistroBitacora,
  KPIsDashboard,
  Distribucion
} from './types';

// Activos ficticios
export const activos: Activo[] = [
  {
    id: '1',
    nombre: 'Pool de Rentas Corporativo Monterrey',
    tipoActivo: 'pool_rentas',
    empresaRelacionada: 'Grupo Patrimonial Norte',
    razonSocial: 'Grupo Patrimonial Norte S.A. de C.V.',
    rfc: 'GPN180501XY7',
    direccionFiscal: 'Av. Constitución 500, Col. Centro, Monterrey, N.L.',
    datosLegales: 'Escritura Pública No. 12345',
    descripcion: 'Pool de 12 departamentos corporativos en zona ejecutiva de Monterrey',
    ubicacion: 'Monterrey, Nuevo León',
    responsableInterno: 'Carlos Mendoza',
    estado: 'generando_rentas',
    valorTotal: 15000000,
    montoInicial: 5000000,
    montoPagado: 15000000,
    montoPendiente: 0,
    formaCompra: 'parcialidades',
    fechaCompra: '2023-06-15',
    fechaRealEntrega: '2023-09-01',
    fechaRealDividendos: '2023-10-01',
    rentabilidadMensualEsperada: 120000,
    rentabilidadAnualEsperada: 1440000,
    porcentajeApreciacion: 5,
    periodicidadDividendos: 'mensual',
    inflacionEstimada: 4.5,
    notasInternas: 'Activo premium con excelente ocupación',
    contactos: [],
    documentos: [],
    porcentajeAdquisicion: 100,
    roi: 9.6,
    payback: 125,
    dividendosAcumulados: 1920000,
    valorActualEstimado: 16500000,
  },
  {
    id: '2',
    nombre: 'Departamento en Renta CDMX Roma Norte',
    tipoActivo: 'inmueble_completo',
    empresaRelacionada: 'Desarrollos Urbanos 1D10',
    razonSocial: 'Desarrollos Urbanos 1D10 S.A. de C.V.',
    rfc: 'DU1D210315AB9',
    direccionFiscal: 'Av. Insurgentes Sur 1000, Col. Del Valle, CDMX',
    datosLegales: 'Escritura Pública No. 54321',
    descripcion: 'Departamento de 120m² en zona premium de Roma Norte',
    ubicacion: 'Ciudad de México, CDMX',
    responsableInterno: 'Ana García',
    estado: 'generando_rentas',
    valorTotal: 4500000,
    montoInicial: 1500000,
    montoPagado: 4500000,
    montoPendiente: 0,
    formaCompra: 'parcialidades',
    fechaCompra: '2023-03-10',
    fechaRealEntrega: '2023-05-01',
    fechaRealDividendos: '2023-06-01',
    rentabilidadMensualEsperada: 35000,
    rentabilidadAnualEsperada: 420000,
    porcentajeApreciacion: 6,
    periodicidadDividendos: 'mensual',
    inflacionEstimada: 4.5,
    notasInternas: 'Ubicación privilegiada, alta demanda',
    contactos: [],
    documentos: [],
    porcentajeAdquisicion: 100,
    roi: 9.3,
    payback: 129,
    dividendosAcumulados: 770000,
    valorActualEstimado: 5100000,
  },
  {
    id: '3',
    nombre: 'Camión de Carga Refrigerado T-800',
    tipoActivo: 'camion_renta',
    empresaRelacionada: 'Logística Activa del Bajío',
    razonSocial: 'Logística Activa del Bajío S.A. de C.V.',
    rfc: 'LAB200820CD3',
    direccionFiscal: 'Blvd. López Mateos 2000, León, Gto.',
    datosLegales: 'Factura de compra y contrato de arrendamiento',
    descripcion: 'Camión refrigerado Kenworth T-800 modelo 2023',
    ubicacion: 'León, Guanajuato',
    responsableInterno: 'Roberto Sánchez',
    estado: 'generando_rentas',
    valorTotal: 2800000,
    montoInicial: 1000000,
    montoPagado: 2800000,
    montoPendiente: 0,
    formaCompra: 'contado',
    fechaCompra: '2024-01-20',
    fechaRealEntrega: '2024-02-01',
    fechaRealDividendos: '2024-03-01',
    rentabilidadMensualEsperada: 45000,
    rentabilidadAnualEsperada: 540000,
    porcentajeApreciacion: -8,
    periodicidadDividendos: 'mensual',
    inflacionEstimada: 4.5,
    notasInternas: 'Contrato de renta con empresa de alimentos congelados',
    contactos: [],
    documentos: [],
    porcentajeAdquisicion: 100,
    roi: 19.3,
    payback: 62,
    dividendosAcumulados: 630000,
    valorActualEstimado: 2520000,
  },
  {
    id: '4',
    nombre: 'Local Comercial Plaza Querétaro',
    tipoActivo: 'local_comercial',
    empresaRelacionada: 'Pool Rentas Capital',
    razonSocial: 'Pool Rentas Capital S.A. de C.V.',
    rfc: 'PRC190215EF5',
    direccionFiscal: 'Av. 5 de Febrero 100, Querétaro, Qro.',
    datosLegales: 'Escritura Pública No. 98765',
    descripcion: 'Local comercial de 85m² en plaza comercial de alto tráfico',
    ubicacion: 'Querétaro, Querétaro',
    responsableInterno: 'María López',
    estado: 'en_pago',
    valorTotal: 3200000,
    montoInicial: 1000000,
    montoPagado: 2400000,
    montoPendiente: 800000,
    formaCompra: 'parcialidades',
    fechaCompra: '2024-06-01',
    fechaLimitePago: '2025-06-01',
    fechaEstimadaEntrega: '2025-03-01',
    fechaEstimadaDividendos: '2025-04-01',
    rentabilidadMensualEsperada: 28000,
    rentabilidadAnualEsperada: 336000,
    porcentajeApreciacion: 4,
    periodicidadDividendos: 'mensual',
    inflacionEstimada: 4.5,
    notasInternas: 'Pagos mensuales de $200,000',
    contactos: [],
    documentos: [],
    porcentajeAdquisicion: 75,
    roi: 0,
    payback: 0,
    dividendosAcumulados: 0,
    valorActualEstimado: 3350000,
  },
  {
    id: '5',
    nombre: 'Participación Industrial Guadalajara',
    tipoActivo: 'participacion_parcial',
    empresaRelacionada: 'Rentas Industriales MX',
    razonSocial: 'Rentas Industriales MX S.A. de C.V.',
    rfc: 'RIM170630GH1',
    direccionFiscal: 'Periférico Sur 5000, Guadalajara, Jal.',
    datosLegales: 'Contrato de participación y fideicomiso',
    descripcion: 'Participación del 25% en nave industrial de 5,000m²',
    ubicacion: 'Guadalajara, Jalisco',
    responsableInterno: 'Carlos Mendoza',
    estado: 'en_proceso_compra',
    valorTotal: 8000000,
    montoInicial: 2000000,
    montoPagado: 3500000,
    montoPendiente: 4500000,
    formaCompra: 'parcialidades',
    fechaCompra: '2024-09-15',
    fechaLimitePago: '2025-09-15',
    fechaEstimadaEntrega: '2025-06-01',
    fechaEstimadaDividendos: '2025-07-01',
    rentabilidadMensualEsperada: 65000,
    rentabilidadAnualEsperada: 780000,
    porcentajeApreciacion: 5,
    periodicidadDividendos: 'mensual',
    inflacionEstimada: 4.5,
    notasInternas: 'Inquilino AAA con contrato a 10 años',
    contactos: [],
    documentos: [],
    porcentajeAdquisicion: 43.75,
    roi: 0,
    payback: 0,
    dividendosAcumulados: 0,
    valorActualEstimado: 8200000,
  },
  {
    id: '6',
    nombre: 'Terreno Riviera Maya',
    tipoActivo: 'terreno',
    empresaRelacionada: 'Desarrollos Urbanos 1D10',
    razonSocial: 'Desarrollos Urbanos 1D10 S.A. de C.V.',
    rfc: 'DU1D210315AB9',
    direccionFiscal: 'Av. Insurgentes Sur 1000, Col. Del Valle, CDMX',
    datosLegales: 'Escritura Pública No. 11223',
    descripcion: 'Terreno de 2,500m² en zona de desarrollo turístico',
    ubicacion: 'Tulum, Quintana Roo',
    responsableInterno: 'Ana García',
    estado: 'en_negociacion',
    valorTotal: 12000000,
    montoInicial: 0,
    montoPagado: 500000,
    montoPendiente: 11500000,
    formaCompra: 'parcialidades',
    fechaCompra: '2025-01-10',
    fechaLimitePago: '2026-01-10',
    rentabilidadMensualEsperada: 0,
    rentabilidadAnualEsperada: 0,
    porcentajeApreciacion: 12,
    periodicidadDividendos: 'mensual',
    inflacionEstimada: 4.5,
    notasInternas: 'En negociación de precio final',
    contactos: [],
    documentos: [],
    porcentajeAdquisicion: 4.17,
    roi: 0,
    payback: 0,
    dividendosAcumulados: 0,
    valorActualEstimado: 12500000,
  },
  {
    id: '7',
    nombre: 'Pool de Rentas Empresariales Guadalajara',
    tipoActivo: 'pool_rentas',
    empresaRelacionada: 'Pool Rentas Capital',
    razonSocial: 'Pool Rentas Capital S.A. de C.V.',
    rfc: 'PRC190215EF5',
    direccionFiscal: 'Av. 5 de Febrero 100, Querétaro, Qro.',
    datosLegales: 'Escritura Pública No. 77889',
    descripcion: 'Pool de 8 oficinas corporativas en zona financiera',
    ubicacion: 'Guadalajara, Jalisco',
    responsableInterno: 'Roberto Sánchez',
    estado: 'en_analisis',
    valorTotal: 9500000,
    montoInicial: 0,
    montoPagado: 0,
    montoPendiente: 9500000,
    formaCompra: 'parcialidades',
    fechaCompra: '',
    rentabilidadMensualEsperada: 85000,
    rentabilidadAnualEsperada: 1020000,
    porcentajeApreciacion: 4,
    periodicidadDividendos: 'mensual',
    inflacionEstimada: 4.5,
    notasInternas: 'En proceso de análisis financiero',
    contactos: [],
    documentos: [],
    porcentajeAdquisicion: 0,
    roi: 0,
    payback: 0,
    dividendosAcumulados: 0,
    valorActualEstimado: 9500000,
  },
];

// Pagos ficticios
export const pagos: Pago[] = [
  {
    id: '1',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    tipoPago: 'anticipo',
    fecha: '2023-06-15',
    monto: 5000000,
    metodoPago: 'Transferencia',
    cuentaBancariaOrigen: 'BBVA 1234',
    destinatario: 'Grupo Patrimonial Norte',
    empresaReceptora: 'Grupo Patrimonial Norte S.A. de C.V.',
    concepto: 'Anticipo por compra de pool de rentas',
    responsable: 'Carlos Mendoza',
    comentarios: 'Pago inicial acordado',
    estatus: 'realizado',
  },
  {
    id: '2',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    tipoPago: 'parcialidad',
    fecha: '2023-07-15',
    monto: 5000000,
    metodoPago: 'Transferencia',
    cuentaBancariaOrigen: 'BBVA 1234',
    destinatario: 'Grupo Patrimonial Norte',
    empresaReceptora: 'Grupo Patrimonial Norte S.A. de C.V.',
    concepto: 'Segunda parcialidad',
    responsable: 'Carlos Mendoza',
    comentarios: '',
    estatus: 'realizado',
  },
  {
    id: '3',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    tipoPago: 'liquidacion',
    fecha: '2023-08-15',
    monto: 5000000,
    metodoPago: 'Transferencia',
    cuentaBancariaOrigen: 'BBVA 1234',
    destinatario: 'Grupo Patrimonial Norte',
    empresaReceptora: 'Grupo Patrimonial Norte S.A. de C.V.',
    concepto: 'Liquidación final',
    responsable: 'Carlos Mendoza',
    comentarios: '',
    estatus: 'realizado',
  },
  {
    id: '4',
    activoId: '4',
    activoNombre: 'Local Comercial Plaza Querétaro',
    tipoPago: 'parcialidad',
    fecha: '2025-05-01',
    monto: 200000,
    metodoPago: 'Transferencia',
    cuentaBancariaOrigen: 'Santander 5678',
    destinatario: 'Pool Rentas Capital',
    empresaReceptora: 'Pool Rentas Capital S.A. de C.V.',
    concepto: 'Parcialidad mayo 2025',
    responsable: 'María López',
    comentarios: 'Próximo pago programado',
    estatus: 'comprometido',
  },
  {
    id: '5',
    activoId: '5',
    activoNombre: 'Participación Industrial Guadalajara',
    tipoPago: 'parcialidad',
    fecha: '2025-05-15',
    monto: 500000,
    metodoPago: 'Transferencia',
    cuentaBancariaOrigen: 'BBVA 1234',
    destinatario: 'Rentas Industriales MX',
    empresaReceptora: 'Rentas Industriales MX S.A. de C.V.',
    concepto: 'Parcialidad mayo 2025',
    responsable: 'Carlos Mendoza',
    comentarios: '',
    estatus: 'comprometido',
  },
];

// Dividendos ficticios
export const dividendos: Dividendo[] = [
  {
    id: '1',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Abril 2025',
    fechaRecepcion: '2025-04-05',
    montoEsperado: 120000,
    montoRecibido: 118500,
    diferencia: -1500,
    comentarios: 'Descuento por mantenimiento',
    estatus: 'recibido',
    responsable: 'Carlos Mendoza',
  },
  {
    id: '2',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Mayo 2025',
    fechaRecepcion: '2025-05-05',
    montoEsperado: 120000,
    montoRecibido: 120000,
    diferencia: 0,
    comentarios: '',
    estatus: 'recibido',
    responsable: 'Carlos Mendoza',
  },
  {
    id: '3',
    activoId: '2',
    activoNombre: 'Departamento en Renta CDMX Roma Norte',
    periodo: 'Abril 2025',
    fechaRecepcion: '2025-04-03',
    montoEsperado: 35000,
    montoRecibido: 35000,
    diferencia: 0,
    comentarios: '',
    estatus: 'recibido',
    responsable: 'Ana García',
  },
  {
    id: '4',
    activoId: '2',
    activoNombre: 'Departamento en Renta CDMX Roma Norte',
    periodo: 'Mayo 2025',
    fechaRecepcion: '2025-05-03',
    montoEsperado: 35000,
    montoRecibido: 35000,
    diferencia: 0,
    comentarios: '',
    estatus: 'recibido',
    responsable: 'Ana García',
  },
  {
    id: '5',
    activoId: '3',
    activoNombre: 'Camión de Carga Refrigerado T-800',
    periodo: 'Abril 2025',
    fechaRecepcion: '2025-04-10',
    montoEsperado: 45000,
    montoRecibido: 45000,
    diferencia: 0,
    comentarios: '',
    estatus: 'recibido',
    responsable: 'Roberto Sánchez',
  },
  {
    id: '6',
    activoId: '3',
    activoNombre: 'Camión de Carga Refrigerado T-800',
    periodo: 'Mayo 2025',
    fechaRecepcion: '',
    montoEsperado: 45000,
    montoRecibido: 0,
    diferencia: -45000,
    comentarios: 'Pendiente de recibir',
    estatus: 'pendiente',
    responsable: 'Roberto Sánchez',
  },
];

// Inversionistas ficticios
export const inversionistas: Inversionista[] = [
  {
    id: '1',
    nombre: 'Enrique Guzmán',
    correo: 'enrique.guzman@email.com',
    telefono: '+52 81 1234 5678',
    rfc: 'GUHE800515AB1',
    direccion: 'Av. Revolución 500, San Pedro Garza García, N.L.',
    cuentaBancaria: '1234567890',
    clabe: '012580001234567890',
    banco: 'BBVA',
    porcentajeParticipacion: 35,
    montoInvertido: 12500000,
    activosRelacionados: ['1', '2', '3'],
    documentos: [],
    estatus: 'activo',
    fechaAlta: '2022-01-15',
    notasInternas: 'Inversionista fundador',
    dividendosEsperados: 70000,
    dividendosRecibidos: 1162500,
    dividendosPagados: 1100000,
    dividendosPendientes: 62500,
    roi: 9.3,
    payback: 129,
  },
  {
    id: '2',
    nombre: 'Keila Hernández',
    correo: 'keila.hernandez@email.com',
    telefono: '+52 55 9876 5432',
    rfc: 'HERK850720CD2',
    direccion: 'Paseo de la Reforma 300, CDMX',
    cuentaBancaria: '0987654321',
    clabe: '014180009876543210',
    banco: 'Santander',
    porcentajeParticipacion: 25,
    montoInvertido: 8750000,
    activosRelacionados: ['1', '4'],
    documentos: [],
    estatus: 'activo',
    fechaAlta: '2022-06-20',
    notasInternas: 'Inversionista estratégica',
    dividendosEsperados: 50000,
    dividendosRecibidos: 812500,
    dividendosPagados: 750000,
    dividendosPendientes: 62500,
    roi: 9.3,
    payback: 129,
  },
  {
    id: '3',
    nombre: 'Inversionista Patrimonial 01',
    correo: 'patrimonial01@inversiones.com',
    telefono: '+52 33 5555 1234',
    rfc: 'IP01191105EF3',
    direccion: 'Av. Américas 1000, Guadalajara, Jal.',
    cuentaBancaria: '5555666677',
    clabe: '021320055556666770',
    banco: 'HSBC',
    porcentajeParticipacion: 20,
    montoInvertido: 7000000,
    activosRelacionados: ['5', '6'],
    documentos: [],
    estatus: 'activo',
    fechaAlta: '2023-03-10',
    notasInternas: 'Fideicomiso de inversión',
    dividendosEsperados: 0,
    dividendosRecibidos: 0,
    dividendosPagados: 0,
    dividendosPendientes: 0,
    roi: 0,
    payback: 0,
  },
  {
    id: '4',
    nombre: 'Capital Privado MX',
    correo: 'contacto@capitalprivadomx.com',
    telefono: '+52 81 8888 9999',
    rfc: 'CPM180310GH4',
    direccion: 'Torre Sofía, Monterrey, N.L.',
    cuentaBancaria: '8888999911',
    clabe: '012580088889999110',
    banco: 'BBVA',
    porcentajeParticipacion: 15,
    montoInvertido: 5250000,
    activosRelacionados: ['1', '3'],
    documentos: [],
    estatus: 'activo',
    fechaAlta: '2023-08-01',
    notasInternas: 'Fondo de inversión privado',
    dividendosEsperados: 30000,
    dividendosRecibidos: 577500,
    dividendosPagados: 550000,
    dividendosPendientes: 27500,
    roi: 11,
    payback: 109,
  },
  {
    id: '5',
    nombre: 'Socio Estratégico Norte',
    correo: 'socio.norte@empresas.com',
    telefono: '+52 81 7777 8888',
    rfc: 'SEN200625IJ5',
    direccion: 'Av. Lázaro Cárdenas 2000, Monterrey, N.L.',
    cuentaBancaria: '7777888822',
    clabe: '012580077778888220',
    banco: 'BBVA',
    porcentajeParticipacion: 5,
    montoInvertido: 1500000,
    activosRelacionados: ['2'],
    documentos: [],
    estatus: 'activo',
    fechaAlta: '2024-01-15',
    notasInternas: 'Inversionista nuevo',
    dividendosEsperados: 10000,
    dividendosRecibidos: 175000,
    dividendosPagados: 150000,
    dividendosPendientes: 25000,
    roi: 11.7,
    payback: 103,
  },
];

// Movimientos financieros ficticios
export const movimientos: MovimientoFinanciero[] = [
  {
    id: '1',
    tipo: 'ingreso',
    categoria: 'rentas',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    fecha: '2025-05-05',
    monto: 120000,
    cuentaBancaria: 'BBVA 1234',
    metodoPago: 'Transferencia',
    responsable: 'Carlos Mendoza',
    comentarios: 'Renta mayo 2025',
    estatus: 'confirmado',
  },
  {
    id: '2',
    tipo: 'ingreso',
    categoria: 'rentas',
    activoId: '2',
    activoNombre: 'Departamento en Renta CDMX Roma Norte',
    fecha: '2025-05-03',
    monto: 35000,
    cuentaBancaria: 'Santander 5678',
    metodoPago: 'Transferencia',
    responsable: 'Ana García',
    comentarios: 'Renta mayo 2025',
    estatus: 'confirmado',
  },
  {
    id: '3',
    tipo: 'ingreso',
    categoria: 'rentas',
    activoId: '3',
    activoNombre: 'Camión de Carga Refrigerado T-800',
    fecha: '2025-04-10',
    monto: 45000,
    cuentaBancaria: 'BBVA 1234',
    metodoPago: 'Transferencia',
    responsable: 'Roberto Sánchez',
    comentarios: 'Renta abril 2025',
    estatus: 'confirmado',
  },
  {
    id: '4',
    tipo: 'egreso',
    categoria: 'mantenimiento',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    fecha: '2025-04-20',
    monto: 15000,
    cuentaBancaria: 'BBVA 1234',
    metodoPago: 'Transferencia',
    responsable: 'Carlos Mendoza',
    comentarios: 'Mantenimiento preventivo',
    estatus: 'confirmado',
  },
  {
    id: '5',
    tipo: 'egreso',
    categoria: 'dividendos_pagados',
    inversionistaId: '1',
    inversionistaNombre: 'Enrique Guzmán',
    fecha: '2025-05-01',
    monto: 42000,
    cuentaBancaria: 'BBVA 1234',
    metodoPago: 'Transferencia',
    responsable: 'Ana García',
    comentarios: 'Dividendos abril 2025',
    estatus: 'confirmado',
  },
  {
    id: '6',
    tipo: 'egreso',
    categoria: 'administracion',
    fecha: '2025-05-01',
    monto: 25000,
    cuentaBancaria: 'Santander 5678',
    metodoPago: 'Transferencia',
    responsable: 'María López',
    comentarios: 'Gastos administrativos mayo 2025',
    estatus: 'confirmado',
  },
];

// Alertas ficticias
export const alertas: Alerta[] = [
  {
    id: '1',
    tipo: 'pago_proximo_vencer',
    nivel: 'amarillo',
    titulo: 'Pago próximo a vencer',
    descripcion: 'El pago de $200,000 para Local Comercial Plaza Querétaro vence el 01/06/2025',
    activoId: '4',
    activoNombre: 'Local Comercial Plaza Querétaro',
    fecha: '2025-05-09',
    estatus: 'pendiente',
  },
  {
    id: '2',
    tipo: 'pago_proximo_vencer',
    nivel: 'amarillo',
    titulo: 'Pago próximo a vencer',
    descripcion: 'El pago de $500,000 para Participación Industrial Guadalajara vence el 15/05/2025',
    activoId: '5',
    activoNombre: 'Participación Industrial Guadalajara',
    fecha: '2025-05-09',
    estatus: 'pendiente',
  },
  {
    id: '3',
    tipo: 'renta_no_recibida',
    nivel: 'rojo',
    titulo: 'Renta pendiente de recibir',
    descripcion: 'No se ha recibido la renta de mayo 2025 del Camión de Carga Refrigerado T-800',
    activoId: '3',
    activoNombre: 'Camión de Carga Refrigerado T-800',
    fecha: '2025-05-09',
    estatus: 'pendiente',
  },
  {
    id: '4',
    tipo: 'falta_documentacion',
    nivel: 'amarillo',
    titulo: 'Documentación incompleta',
    descripcion: 'Faltan documentos obligatorios para Terreno Riviera Maya',
    activoId: '6',
    activoNombre: 'Terreno Riviera Maya',
    fecha: '2025-05-08',
    estatus: 'en_revision',
  },
  {
    id: '5',
    tipo: 'activo_proximo_dividendos',
    nivel: 'verde',
    titulo: 'Próximo inicio de dividendos',
    descripcion: 'Local Comercial Plaza Querétaro iniciará dividendos en abril 2025',
    activoId: '4',
    activoNombre: 'Local Comercial Plaza Querétaro',
    fecha: '2025-05-07',
    estatus: 'pendiente',
  },
];

// Distribuciones a Inversionistas
export const distribuciones: Distribucion[] = [
  {
    id: 'dist-1',
    inversionistaId: '1',
    inversionistaNombre: 'Enrique Guzmán',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Abril 2025',
    fechaProgramada: '2025-05-05',
    fechaPago: '2025-05-05',
    montoCalculado: 42000,
    montoPagado: 42000,
    porcentajeParticipacion: 35,
    metodoPago: 'transferencia',
    cuentaDestino: '1234567890',
    bancoDestino: 'BBVA',
    referencia: 'TRF-2025-0501',
    estatus: 'pagado',
    comentarios: 'Pago puntual correspondiente a abril',
    creadoPor: 'Carlos Mendoza',
    fechaCreacion: '2025-05-01',
  },
  {
    id: 'dist-2',
    inversionistaId: '2',
    inversionistaNombre: 'Keila Hernández',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Abril 2025',
    fechaProgramada: '2025-05-05',
    fechaPago: '2025-05-05',
    montoCalculado: 30000,
    montoPagado: 30000,
    porcentajeParticipacion: 25,
    metodoPago: 'transferencia',
    cuentaDestino: '0987654321',
    bancoDestino: 'Santander',
    referencia: 'TRF-2025-0502',
    estatus: 'pagado',
    comentarios: 'Pago puntual correspondiente a abril',
    creadoPor: 'Carlos Mendoza',
    fechaCreacion: '2025-05-01',
  },
  {
    id: 'dist-3',
    inversionistaId: '4',
    inversionistaNombre: 'Capital Privado MX',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Abril 2025',
    fechaProgramada: '2025-05-05',
    fechaPago: '2025-05-06',
    montoCalculado: 18000,
    montoPagado: 18000,
    porcentajeParticipacion: 15,
    metodoPago: 'transferencia',
    cuentaDestino: '8888999911',
    bancoDestino: 'BBVA',
    referencia: 'TRF-2025-0503',
    estatus: 'pagado',
    comentarios: 'Pago un día después por validación bancaria',
    creadoPor: 'Carlos Mendoza',
    fechaCreacion: '2025-05-01',
  },
  {
    id: 'dist-4',
    inversionistaId: '1',
    inversionistaNombre: 'Enrique Guzmán',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Mayo 2025',
    fechaProgramada: '2025-06-05',
    montoCalculado: 42000,
    montoPagado: 0,
    porcentajeParticipacion: 35,
    metodoPago: 'transferencia',
    cuentaDestino: '1234567890',
    bancoDestino: 'BBVA',
    estatus: 'programado',
    creadoPor: 'Carlos Mendoza',
    fechaCreacion: '2025-05-15',
  },
  {
    id: 'dist-5',
    inversionistaId: '2',
    inversionistaNombre: 'Keila Hernández',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Mayo 2025',
    fechaProgramada: '2025-06-05',
    montoCalculado: 30000,
    montoPagado: 0,
    porcentajeParticipacion: 25,
    metodoPago: 'transferencia',
    cuentaDestino: '0987654321',
    bancoDestino: 'Santander',
    estatus: 'programado',
    creadoPor: 'Carlos Mendoza',
    fechaCreacion: '2025-05-15',
  },
  {
    id: 'dist-6',
    inversionistaId: '4',
    inversionistaNombre: 'Capital Privado MX',
    activoId: '1',
    activoNombre: 'Pool de Rentas Corporativo Monterrey',
    periodo: 'Mayo 2025',
    fechaProgramada: '2025-06-05',
    montoCalculado: 18000,
    montoPagado: 0,
    porcentajeParticipacion: 15,
    metodoPago: 'transferencia',
    cuentaDestino: '8888999911',
    bancoDestino: 'BBVA',
    estatus: 'programado',
    creadoPor: 'Carlos Mendoza',
    fechaCreacion: '2025-05-15',
  },
  {
    id: 'dist-7',
    inversionistaId: '1',
    inversionistaNombre: 'Enrique Guzmán',
    activoId: '2',
    activoNombre: 'Departamento en Renta CDMX Roma Norte',
    periodo: 'Abril 2025',
    fechaProgramada: '2025-05-05',
    fechaPago: '2025-05-05',
    montoCalculado: 17500,
    montoPagado: 17500,
    porcentajeParticipacion: 50,
    metodoPago: 'transferencia',
    cuentaDestino: '1234567890',
    bancoDestino: 'BBVA',
    referencia: 'TRF-2025-0504',
    estatus: 'pagado',
    creadoPor: 'Ana García',
    fechaCreacion: '2025-05-01',
  },
  {
    id: 'dist-8',
    inversionistaId: '2',
    inversionistaNombre: 'Keila Hernández',
    activoId: '2',
    activoNombre: 'Departamento en Renta CDMX Roma Norte',
    periodo: 'Abril 2025',
    fechaProgramada: '2025-05-05',
    montoCalculado: 17500,
    montoPagado: 10000,
    porcentajeParticipacion: 50,
    metodoPago: 'transferencia',
    cuentaDestino: '0987654321',
    bancoDestino: 'Santander',
    referencia: 'TRF-2025-0505',
    estatus: 'parcial',
    comentarios: 'Pago parcial, pendiente $7,500',
    creadoPor: 'Ana García',
    fechaCreacion: '2025-05-01',
  },
  {
    id: 'dist-9',
    inversionistaId: '3',
    inversionistaNombre: 'Inversionista Patrimonial 01',
    activoId: '5',
    activoNombre: 'Nave Industrial Querétaro',
    periodo: 'Marzo 2025',
    fechaProgramada: '2025-04-10',
    montoCalculado: 45000,
    montoPagado: 0,
    porcentajeParticipacion: 60,
    metodoPago: 'transferencia',
    cuentaDestino: '5555666677',
    bancoDestino: 'HSBC',
    estatus: 'pendiente',
    comentarios: 'Pendiente de validación de datos bancarios',
    creadoPor: 'Carlos Mendoza',
    fechaCreacion: '2025-04-01',
  },
];

// Usuarios de Agency 4 Real Estate
export const usuarios: Usuario[] = [
  {
    id: '1',
    nombre: 'Enrique Guzmán',
    email: 'enrique@agency4realestate.com',
    avatar: undefined,
    rol: 'super_admin',
    permisos: {
      ver: true,
      crear: true,
      editar: true,
      eliminar: true,
      exportar: true,
      aprobar: true,
      subirDocumentos: true,
      registrarPagos: true,
      registrarIngresos: true,
      registrarEgresos: true,
      verInfoFinanciera: true,
      verReportes: true,
      administrarUsuarios: true,
      cambiarConfiguracion: true,
    },
    activo: true,
    ultimoAcceso: '2025-05-09T10:30:00',
  },
  {
    id: '2',
    nombre: 'Keila Jozabed Hernandez',
    email: 'keila@agency4realestate.com',
    avatar: undefined,
    rol: 'super_admin',
    permisos: {
      ver: true,
      crear: true,
      editar: true,
      eliminar: true,
      exportar: true,
      aprobar: true,
      subirDocumentos: true,
      registrarPagos: true,
      registrarIngresos: true,
      registrarEgresos: true,
      verInfoFinanciera: true,
      verReportes: true,
      administrarUsuarios: true,
      cambiarConfiguracion: true,
    },
    activo: true,
    ultimoAcceso: '2025-05-09T09:15:00',
  },
  {
    id: '3',
    nombre: 'Tony Lara',
    email: 'antonio@agency4realestate.com',
    avatar: undefined,
    rol: 'administrador_financiero',
    permisos: {
      ver: true,
      crear: true,
      editar: true,
      eliminar: false,
      exportar: true,
      aprobar: true,
      subirDocumentos: true,
      registrarPagos: true,
      registrarIngresos: true,
      registrarEgresos: true,
      verInfoFinanciera: true,
      verReportes: true,
      administrarUsuarios: false,
      cambiarConfiguracion: false,
    },
    activo: true,
    ultimoAcceso: '2025-05-08T16:45:00',
  },
  {
    id: '4',
    nombre: 'Alejandra',
    email: 'administracion.finanzas@agency4realestate.com',
    avatar: undefined,
    rol: 'administrador_financiero',
    permisos: {
      ver: true,
      crear: true,
      editar: true,
      eliminar: false,
      exportar: true,
      aprobar: true,
      subirDocumentos: true,
      registrarPagos: true,
      registrarIngresos: true,
      registrarEgresos: true,
      verInfoFinanciera: true,
      verReportes: true,
      administrarUsuarios: false,
      cambiarConfiguracion: false,
    },
    activo: true,
    ultimoAcceso: '2025-05-08T14:20:00',
  },
]



// Bitácora - Capital 1D10
export const bitacora: RegistroBitacora[] = [
  {
    id: '1',
    usuarioId: '2',
    usuarioNombre: 'Keila Jozabed Hernandez',
    fecha: '2025-05-09',
    hora: '10:30:00',
    modulo: 'Dividendos',
    accion: 'Registro de dividendo',
    registroAfectado: 'Pool de Rentas Corporativo Monterrey - Mayo 2025',
    valorAnterior: undefined,
    valorNuevo: '$120,000 MXN',
    comentarios: 'Dividendo mensual registrado',
  },
  {
    id: '2',
    usuarioId: '3',
    usuarioNombre: 'Tony Lara',
    fecha: '2025-05-08',
    hora: '15:45:00',
    modulo: 'Activos',
    accion: 'Actualización de estado',
    registroAfectado: 'Local Comercial Plaza Querétaro',
    valorAnterior: 'En proceso de compra',
    valorNuevo: 'En pago',
    comentarios: 'Cambio de estado por avance en pagos',
  },
  {
    id: '3',
    usuarioId: '1',
    usuarioNombre: 'Enrique Guzmán',
    fecha: '2025-05-07',
    hora: '09:00:00',
    modulo: 'Usuarios',
    accion: 'Alta de usuario',
    registroAfectado: 'Alekandra',
    valorAnterior: undefined,
    valorNuevo: 'Usuario creado con rol Gerente',
    comentarios: 'Acceso para administración de finanzas',
  },
  {
    id: '4',
    usuarioId: '4',
    usuarioNombre: 'Alejandra',
    fecha: '2025-05-06',
    hora: '14:20:00',
    modulo: 'Pagos',
    accion: 'Registro de pago',
    registroAfectado: 'Participación Industrial Guadalajara',
    valorAnterior: '$3,000,000',
    valorNuevo: '$3,500,000',
    comentarios: 'Pago de parcialidad realizado',
  },
  {
    id: '5',
    usuarioId: '3',
    usuarioNombre: 'Tony Lara',
    fecha: '2025-05-05',
    hora: '11:10:00',
    modulo: 'Documentos',
    accion: 'Carga de documento',
    registroAfectado: 'Pool de Rentas Corporativo Monterrey',
    valorAnterior: undefined,
    valorNuevo: 'Reporte mensual abril 2025.pdf',
    comentarios: 'Documento subido correctamente',
  },
];

// KPIs del Dashboard
export const kpisDashboard: KPIsDashboard = {
  valorTotalActivos: 55000000,
  totalInvertido: 28700000,
  totalPendientePagar: 26300000,
  porcentajeGlobalAdquisicion: 52.18,
  rentasMensualesEsperadas: 378000,
  rentasMensualesReales: 353500,
  diferenciaRentas: -24500,
  flujoNetoMensual: 268500,
  totalActivos: 7,
  activosEnAnalisis: 1,
  activosEnNegociacion: 1,
  activosEnCompra: 1,
  activosEnPago: 1,
  activosEnEsperaOperacion: 0,
  activosGenerandoRentas: 3,
  activosVendidos: 0,
  rendimientoPromedioMensual: 1.25,
  rendimientoPromedioAnual: 15,
  roiPromedio: 9.8,
  paybackPromedio: 106,
  ebitdaMensual: 293500,
  capitalPendienteRecuperacion: 25380000,
  dividendosPagados: 2550000,
  dividendosPorPagar: 177500,
};

// Datos para gráficas
export const datosGraficaIngresos = [
  { mes: 'Ene', ingresos: 185000, egresos: 95000 },
  { mes: 'Feb', ingresos: 195000, egresos: 88000 },
  { mes: 'Mar', ingresos: 210000, egresos: 102000 },
  { mes: 'Abr', ingresos: 198500, egresos: 85000 },
  { mes: 'May', ingresos: 200000, egresos: 85000 },
];

export const datosGraficaDividendos = [
  { mes: 'Ene', esperados: 200000, reales: 195000 },
  { mes: 'Feb', esperados: 200000, reales: 198500 },
  { mes: 'Mar', esperados: 200000, reales: 200000 },
  { mes: 'Abr', esperados: 200000, reales: 198500 },
  { mes: 'May', esperados: 200000, reales: 155000 },
];

export const datosDistribucionActivos = [
  { nombre: 'Pool de Rentas', valor: 24500000, porcentaje: 44.5 },
  { nombre: 'Inmuebles', valor: 4500000, porcentaje: 8.2 },
  { nombre: 'Camiones', valor: 2800000, porcentaje: 5.1 },
  { nombre: 'Locales', valor: 3200000, porcentaje: 5.8 },
  { nombre: 'Participaciones', valor: 8000000, porcentaje: 14.5 },
  { nombre: 'Terrenos', valor: 12000000, porcentaje: 21.8 },
];

export const datosEvolucionValor = [
  { año: '2023', valor: 22300000 },
  { año: '2024', valor: 35000000 },
  { año: '2025', valor: 55000000 },
  { año: '2026 (Proy)', valor: 68000000 },
  { año: '2027 (Proy)', valor: 82000000 },
];

export const datosProyeccion = [
  { año: 2025, conservador: 55000000, base: 58000000, optimista: 62000000 },
  { año: 2026, conservador: 61000000, base: 68000000, optimista: 76000000 },
  { año: 2027, conservador: 68000000, base: 79000000, optimista: 92000000 },
  { año: 2028, conservador: 75000000, base: 91000000, optimista: 110000000 },
  { año: 2029, conservador: 83000000, base: 105000000, optimista: 130000000 },
  { año: 2030, conservador: 92000000, base: 121000000, optimista: 155000000 },
];

// Aliases para compatibilidad
export const mockUsers = usuarios.map(u => ({
  id: u.id,
  name: u.nombre,
  email: u.email,
  avatar: u.avatar,
  role: u.rol === 'super_admin' ? 'admin' : u.rol === 'administrador_financiero' ? 'manager' : u.rol === 'operador' ? 'analyst' : 'viewer',
  status: u.activo ? 'active' : 'inactive',
  lastLogin: u.ultimoAcceso,
  createdAt: '2024-01-15',
}));

export const mockAuditLogs = bitacora.map(b => ({
  id: b.id,
  userId: b.usuarioId,
  user: b.usuarioNombre,
  action: b.accion.toLowerCase().includes('registro') ? 'create' : b.accion.toLowerCase().includes('actualiza') ? 'update' : b.accion.toLowerCase().includes('elimina') ? 'delete' : 'view',
  module: b.modulo.toLowerCase() === 'dividendos' ? 'payments' : b.modulo.toLowerCase() === 'activos' ? 'assets' : b.modulo.toLowerCase() === 'usuarios' ? 'users' : b.modulo.toLowerCase() === 'pagos' ? 'payments' : b.modulo.toLowerCase() === 'documentos' ? 'documents' : 'settings',
  description: `${b.accion}: ${b.registroAfectado}`,
  timestamp: `${b.fecha}T${b.hora}`,
  ipAddress: '192.168.1.' + (parseInt(b.id) + 100),
  details: b.comentarios || (b.valorAnterior && b.valorNuevo ? `Cambio de "${b.valorAnterior}" a "${b.valorNuevo}"` : undefined),
}));

// Alias para activos
export const mockAssets = activos.map(a => ({
  id: a.id,
  name: a.nombre,
  type: a.tipo,
  location: a.ubicacion,
  value: a.valorActual,
  status: a.estado,
}));

// Registros financieros para la página de finanzas
export const mockFinancialRecords = movimientos.map(m => ({
  id: m.id,
  date: m.fecha,
  description: m.comentarios || m.activoNombre || 'Sin descripción',
  category: m.categoria,
  type: m.tipo === 'ingreso' ? 'income' : 'expense',
  amount: m.monto,
  assetId: m.activoId,
}));

// Reportes para la página de informes
export const mockReports = [
  { id: "1", name: "Balance General Q4 2024", type: "financial", status: "completed", createdAt: "2024-01-15", format: "pdf", size: 2450000, description: "Balance general consolidado del cuarto trimestre 2024" },
  { id: "2", name: "Estado de Resultados Diciembre", type: "financial", status: "completed", createdAt: "2024-01-14", format: "pdf", size: 1800000, description: "Estado de resultados del mes de diciembre" },
  { id: "3", name: "Reporte EBITDA Q4 2024", type: "ebitda", status: "completed", createdAt: "2024-01-13", format: "pdf", size: 3200000, description: "Análisis de EBITDA y márgenes operativos del trimestre" },
  { id: "4", name: "Valuación de Activos Q4", type: "assets", status: "completed", createdAt: "2024-01-12", format: "excel", size: 4500000, description: "Valuación actualizada de todos los activos inmobiliarios" },
  { id: "5", name: "Reporte de Dividendos Q4", type: "investors", status: "completed", createdAt: "2024-01-10", format: "pdf", size: 1200000, description: "Distribución de dividendos a inversionistas Q4" },
  { id: "6", name: "Declaración Fiscal Anual 2023", type: "tax", status: "processing", createdAt: "2024-01-08", format: "pdf", size: 5600000, description: "Declaración fiscal anual en proceso de generación" },
  { id: "7", name: "Rendimiento por Inversionista", type: "investors", status: "completed", createdAt: "2024-01-05", format: "excel", size: 890000, description: "Detalle de rendimientos individuales por inversionista" },
  { id: "8", name: "Flujo de Efectivo Mensual", type: "financial", status: "completed", createdAt: "2024-01-03", format: "pdf", size: 1500000, description: "Flujo de caja consolidado mensual" },
  { id: "9", name: "Análisis de Rentabilidad", type: "assets", status: "completed", createdAt: "2024-01-01", format: "pdf", size: 2100000, description: "Análisis de rentabilidad por activo" },
  { id: "10", name: "EBITDA Anual 2023", type: "ebitda", status: "completed", createdAt: "2023-12-31", format: "excel", size: 4800000, description: "Reporte completo de EBITDA y métricas operativas 2023" },
];

// Alertas para la página de alertas
export const mockAlerts = alertas.map(a => ({
  id: a.id,
  title: a.tipo.charAt(0).toUpperCase() + a.tipo.slice(1).replace(/_/g, ' '),
  description: a.mensaje,
  type: a.nivel === 'rojo' ? 'error' : a.nivel === 'amarillo' ? 'warning' : 'info',
  priority: a.nivel === 'rojo' ? 'high' : a.nivel === 'amarillo' ? 'medium' : 'low',
  status: a.leida ? 'read' : 'unread',
  createdAt: a.fecha,
  assetId: a.activoId,
  assetName: activos.find(ac => ac.id === a.activoId)?.nombre || 'N/A',
}));

// Documentos para la página de documentos
export const mockDocuments = [
  { id: "1", name: "Escritura Propiedad Torres del Valle", type: "legal", category: "Escrituras", size: 2450000, uploadedAt: "2024-01-10", uploadedBy: "Admin Sistema", assetId: "1", assetName: "Torres del Valle" },
  { id: "2", name: "Contrato Arrendamiento Local 205", type: "contract", category: "Contratos", size: 890000, uploadedAt: "2024-01-08", uploadedBy: "Admin Sistema", assetId: "1", assetName: "Torres del Valle" },
  { id: "3", name: "Avaluo Comercial 2024", type: "financial", category: "Valuaciones", size: 1250000, uploadedAt: "2024-01-05", uploadedBy: "Carlos Mendez", assetId: "2", assetName: "Plaza Comercial Reforma" },
  { id: "4", name: "Poliza Seguro Inmueble", type: "insurance", category: "Seguros", size: 560000, uploadedAt: "2024-01-03", uploadedBy: "Admin Sistema", assetId: "3", assetName: "Edificio Corporativo Polanco" },
  { id: "5", name: "Planos Arquitectonicos", type: "technical", category: "Planos", size: 8900000, uploadedAt: "2023-12-20", uploadedBy: "Arq. Rodriguez", assetId: "4", assetName: "Desarrollo Habitacional Norte" },
  { id: "6", name: "Permiso de Construccion", type: "legal", category: "Permisos", size: 450000, uploadedAt: "2023-12-15", uploadedBy: "Admin Sistema", assetId: "4", assetName: "Desarrollo Habitacional Norte" },
  { id: "7", name: "Estados Financieros Q4 2023", type: "financial", category: "Finanzas", size: 1800000, uploadedAt: "2024-01-02", uploadedBy: "CFO", assetId: "general", assetName: "General" },
  { id: "8", name: "Acta Asamblea Inversionistas", type: "legal", category: "Actas", size: 320000, uploadedAt: "2023-12-28", uploadedBy: "Secretario", assetId: "general", assetName: "General" },
];
